Fix error checking
SIGNIFICANTLY stricter than before!
If ANYTHING goes wrong, it exits. Should help prevent infinite loops and misconfigured apt-gets.
If an error occurs during a simulated upgrade, nothing is echoed, since it wouldn't get to the user anyway.

diff --git a/apt-get/update-all b/apt-get/update-all
--- a/apt-get/update-all
+++ b/apt-get/update-all
@@ -1,36 +1,48 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-sudo echo true >/dev/null || (echo "Root is needed to perform an update!" && exit 2)
-
+#sudo do nothing or fail
+sudo true || (echo "Root is needed to perform an upgrade! Abort!" & kill $$)
 echo 'Updating the repository cache...'
-sudo apt-get -ymuq update >/dev/null #update the repository cache
+
+#update the repository cache
+sudo apt-get -ymuq update >/dev/null || (echo "Something went wrong during this stage! Stopping!" & kill $$)
 echo 'Checking for upgraded packages...'
-RET=$(sudo apt-get -qs --assume-no upgrade) #Store the output of a simulated upgrade
+
+#Store the output of a simulated upgrade
+RET=$(sudo apt-get -qs --assume-no upgrade || (kill $$))
 MSG=$(echo -e "Reading package lists...\nBuilding dependency tree...\nReading state information...\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.")
+
 if [ "$RET" = "$MSG" ]; then #$MSG has to be a variable because $RET contains newlines, which we can't get without echoing
   MORE=''
 else
   while [ ! "$RET" = "$MSG" ]; do
+    
+    #upgrade all the 'mundane' programs
     echo 'Upgrading user packages...'
     echo 'Please be patient; this can take a while.'
-    #upgrade all the 'mundane' programs
-    sudo apt-get -ymuq upgrade >/dev/null || (echo "Something went wrong during this stage! If you see this message multiple times, hold down Ctrl-C until this script stops." && sleep 5)
+    sudo apt-get -ymuq upg rade >/dev/null || (echo "Something went wrong during this stage! Stopping!" & kill $$)
+    
+    #upgrade the distro and system files
     echo 'Upgrading distro and system files...'
     echo 'Please be patient; this can take a while.'
-    #upgrade the distro and system files
-    sudo apt-get -ymuq dist-upgrade >/dev/null || (echo "Something went wrong during this stage! If you see this message multiple times, hold down Ctrl-C until this script stops." && sleep 5)
-    echo 'Removing unneeded packages...'
+    sudo apt-get -ymuq dist-upgrade >/dev/null || (echo "Something went wrong during this stage! Stopping!" & kill $$)
+    
     #uninstall all unnecessary/orphaned packages
-    sudo apt-get -ymuq autoremove >/dev/null || (echo "Something went wrong during this stage! If you see this message multiple times, hold down Ctrl-C until this script stops." && sleep 5)
-    echo 'Cleaning up...'
+    echo 'Removing unneeded packages...'
+    sudo apt-get -ymuq autoremove >/dev/null || (echo "Something went wrong during this stage! Stopping!" & kill $$)
+    
     #delete all unnecessary packages left over
-    sudo apt-get -ymuq autoclean >/dev/null || (echo "Something went wrong during this stage! If you see this message multiple times, hold down Ctrl-C until this script stops." && sleep 5)
-    echo 'Updating the repository cache...'
+    echo 'Cleaning up...'
+    sudo apt-get -ymuq autoclean >/dev/null || (echo "Something went wrong during this stage! Stopping!" & kill $$)
+    
     #update the repository cache
-    sudo apt-get -ymuq update >/dev/null || (echo "Something went wrong during this stage! If you see this message multiple times, hold down Ctrl-C until this script stops." && sleep 5)
-    echo 'Checking for more upgraded packages...'
+    echo 'Updating the repository cache...'
+    sudo apt-get -ymuq update >/dev/null || (echo "Something went wrong during this stage! Stopping!" & kill $$)
+    
     #update the simulated upgrade
-    RET=$(sudo apt-get -qs --assume-no upgrade) 
+    echo 'Checking for more upgraded packages...'
+    RET=$(sudo apt-get -qs --assume-no upgrade || (kill $$))
+  
   done
   MORE=' more'
 fi
